resources:
  repositories:
    - repository: templates
      type: git
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe.yml@templates
  parameters:
    package: inchi
    package_version: 1.06
    destination_repository: ccdc-3rdparty-conan
